from typing import Optional

from pydantic import BaseModel, Field

class Root_Agent_Output_Schema(BaseModel):
    response: str = Field(..., description="The response generated by the root agent.")
    action_required: bool = Field(..., description="Indicates whether an action is required based on the response.")
   
    
    
class Math_Agent_Output_Schema(BaseModel):
    problem: str = Field(..., description="The math problem provided by the user.")
    steps :list[str] = Field(..., description="Step-by-step solution to the math problem.")
    code_execution_result: Optional[str] = Field(default=None, description="Result of any code execution related to the math problem.")
    final_answer: str = Field(..., description="The final answer to the math problem.")
    latex_expression: str = Field(..., description="The LaTeX representation of the final answer.")